version: '3'

services:
  abastapp:
    build: .
    command: npm start
    ports:
      - "4000:4000"
    volumes:
      - .:/user/app
    depends_on:
      - db 
  db:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
